/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diu.desk;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

 
public class AdmitCard extends javax.swing.JFrame {

   private static final DateFormat currentDate=new SimpleDateFormat("dd-MM-yyyy");
     Date date=new Date();
     String location=System.getProperty("user.home")+"\\Desktop\\Admit\\";
     Rectangle one;
     Document doc;
     Font font = FontFactory.getFont(FontFactory.TIMES_ROMAN, 16, BaseColor.BLACK);
     PdfPTable table;
     
   
     Image image;
     byte[] imagebyte;
     String semesterNo;
     Connection con = null;
     Statement statement = null;
     PreparedStatement pStatement = null;
     ResultSet rs = null;
  
     ArrayList <String> courseCode=new ArrayList();
     ArrayList <String> courseName=new ArrayList();
     
    
     AdmitCardData acdata=new AdmitCardData();
     
    public AdmitCard() {
        initComponents();
        con = ConnectionFactory.getMysqlConnection();
        batchTf.setText("E-");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        batchTf = new javax.swing.JTextField();
        rollTf = new javax.swing.JTextField();
        mothersNameTf = new javax.swing.JTextField();
        fathersNameTf = new javax.swing.JTextField();
        studentNameTf = new javax.swing.JTextField();
        semesterTf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PrintBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        closebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admit Card");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 69, 79));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 150, 160));

        batchTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                batchTfKeyReleased(evt);
            }
        });
        jPanel1.add(batchTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 90, 40));

        rollTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rollTfKeyReleased(evt);
            }
        });
        jPanel1.add(rollTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 90, 40));
        jPanel1.add(mothersNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 180, 40));
        jPanel1.add(fathersNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 180, 40));
        jPanel1.add(studentNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 180, 40));
        jPanel1.add(semesterTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 180, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Father's Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 180, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Batch No.:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 140, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Roll No.:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 130, 40));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Student's Picture");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 150, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student's Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 180, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mother's Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 180, 40));

        PrintBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PrintBtn.setText("Print Admit");
        PrintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBtnActionPerformed(evt);
            }
        });
        jPanel1.add(PrintBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 180, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ADMIT CARD");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 680, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Current Semester");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 180, 40));

        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_26px.png"))); // NOI18N
        closebtn.setText("Close");
        closebtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        jPanel1.add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void batchTfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_batchTfKeyReleased
        try {
                 
                String Ssql="SELECT * FROM  batchinfo WHERE batch=?";
                pStatement=con.prepareStatement(Ssql);
                
                pStatement.setString(1,batchTf.getText());
                rs=pStatement.executeQuery();
                if(rs.next()){
                    semesterNo=rs.getString("semester");
                    semesterTf.setText(semesterNo);
             }
                
            pStatement=con.prepareStatement("SELECT course_code,course_title FROM courseinfo WHERE semester=?");
            pStatement.setString(1, semesterTf.getText());
            rs=pStatement.executeQuery();
            while(rs.next()){
                String courseCodeGet=rs.getString("course_code");
                courseCode.add(courseCodeGet);
                String courseNameGet=rs.getString("course_title");
                courseName.add(courseNameGet);
                            }
            CourseCodeArrayClear();
            CourseNameArrayClear();
          
             
                System.out.println(courseCode+" "+courseName.size());
           
           
            if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE){
                    clearLabel();
                } 
            } 
            
            catch (Exception ex) {
                    Logger.getLogger(AdmitCard.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_batchTfKeyReleased

    private void rollTfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rollTfKeyReleased
         try{
                  
             String Ssql="SELECT * FROM studentinfo WHERE roll=? and batch=? ";         
                 pStatement=con.prepareStatement(Ssql);   
                
                 pStatement.setString(1,rollTf.getText());
                 pStatement.setString(2,batchTf.getText());
                  rs=pStatement.executeQuery();
                  if(rs.next()){
                            acdata.setFathersName(rs.getString("fathers_name"));
                            acdata.setMothersName(rs.getString("mothers_name"));
                            acdata.setName(rs.getString("student_name"));
                            acdata.setBatch(rs.getString("batch"));
                            acdata.setRoll(rs.getString("roll"));
                            acdata.setSemester(rs.getString("semester"));
                            acdata.setDepartment(rs.getString("department"));
                            acdata.setStudentId(rs.getString("student_id"));
                            
                           mothersNameTf.setText(rs.getString("fathers_name"));
                           fathersNameTf.setText(rs.getString("mothers_name"));
                           studentNameTf.setText(rs.getString("student_name"));
                           imagebyte=rs.getBytes("image"); 
                           java.awt.Image awtImage=getToolkit().createImage(imagebyte);
                           image = com.itextpdf.text.Image.getInstance(awtImage, null);
                          
                         java.awt.Image reSiezedimg = awtImage.getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(),awtImage.SCALE_SMOOTH);
                         ImageIcon icon=new ImageIcon(reSiezedimg);
                         
                           imageLabel.setIcon(icon);
                           
                         }
              
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_rollTfKeyReleased

    private void PrintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBtnActionPerformed
       AdmitGenerate();
    }//GEN-LAST:event_PrintBtnActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    public void clearLabel(){
         rollTf.setText("");
         mothersNameTf.setText("");
         fathersNameTf.setText("");
         studentNameTf.setText("");
         semesterTf.setText("");
         courseCode.clear();
         courseName.clear();
    }
    
       public void CourseCodeArrayClear(){
                HashSet hcc=new HashSet();
                hcc.addAll(courseCode);
                courseCode.clear();
                courseCode.addAll(hcc);
                
    }
       public void CourseNameArrayClear(){
                HashSet hcn=new HashSet();
                hcn.addAll(courseName);
                courseName.clear();
                courseName.addAll(hcn);
                
    }
       public void AdmitGenerate(){
    //Make File end here
       String SALTCHARS = "1234567890";
        StringBuilder rendomkey = new StringBuilder();
        Random rnd = new Random();
        while (rendomkey.length() < 5) { // length of the random string.
            int index = (int) (rnd.nextFloat() * SALTCHARS.length());
            rendomkey.append(SALTCHARS.charAt(index));
        }
        String generatedKey = rendomkey.toString();   
        //Generate a rendom key here 
       

        File file=new File(location);
            if(!file.exists())
            {
                file.mkdir();
            }
            try{
                doc=new Document();
                one = new Rectangle(797,696);
                PdfWriter writer = PdfWriter.getInstance(doc,new FileOutputStream(location+"Admit of DIU "+generatedKey+".pdf"));
                doc.setPageSize(one);
                doc.setMargins(10, 10, 10, 10);
                doc.open();
                
                 
                    Paragraph pUniversityName= new Paragraph("Dhaka International University",font);
                    Paragraph pAddress= new Paragraph("Administrative Building,House#04, Road#01, Block #F Banani, Dhaka1213.\n\n\n");
                    
                    Paragraph pRoll=new Paragraph("Exam Roll No :"+acdata.getRoll()+"\n");
                    Paragraph pBatch=new Paragraph("Batch No :"+acdata.getBatch()+"\n");
                    
                    Paragraph p4=new Paragraph("\n\n\n                   Department      "+acdata.getDepartment()+"                                       \n\n\n");
                    Paragraph p5=new Paragraph("                   Full Name of the Examinee : "+acdata.getName()+"\n");
                    Paragraph p6=new Paragraph("                   Father's Name: "+acdata.getFathersName());
                    Paragraph p7=new Paragraph("                   Mother's Name: "+acdata.getMothersName());
                    Paragraph p8=new Paragraph("                   Courses' name for apperaring at the Examinations: (1) "+courseName.get(0)+" ( "+courseCode.get(0)+" ).");
                    Paragraph p9=new Paragraph("                   (2) "+courseName.get(1)+" ( "+courseCode.get(1)+" ). "+" (3) "+courseName.get(2)+" ( "+courseCode.get(2)+" )");

                    
                    pUniversityName.setAlignment(Paragraph.ALIGN_CENTER);
                    pAddress.setAlignment(Paragraph.ALIGN_CENTER); 
                    pRoll.setIndentationLeft(620);
                    pBatch.setIndentationLeft(620);
                    
                   image.scaleAbsoluteHeight(120);
                   image.scaleAbsoluteWidth((image.getWidth() * 110) /image.getHeight());
                   image.setAbsolutePosition(45,530);
                 
                  // Image diulogo=Image.getInstance("src/images/DiuLogo.png");
                 //  diulogo.scaleAbsoluteHeight(26);
                  // diulogo.scaleAbsoluteWidth(50);
                  //  diulogo.setAbsolutePosition(375,595);
                    
                    doc.add(pUniversityName);
                    doc.add(pAddress);
                    doc.add(pRoll);
                    doc.add(pBatch);
                    doc.add(p4);
                    
                    doc.add(image);
//                    doc.add(diulogo);
                    
                    doc.add(p5);
                    doc.add(p6);
                    doc.add(p7);
                    doc.add(p8);
                    doc.add(p9);
                    if(courseName.size()>4){
                       Paragraph p10=new Paragraph("                   (4) "+courseName.get(3)+" ( "+courseCode.get(3)+" ). "+" (5) "+courseName.get(4)+" ( "+courseCode.get(4)+" )");
                        doc.add(p10);
                    }
                    if(courseName.size()>5){
                       Paragraph p11=new Paragraph("                   (6) "+courseName.get(5)+" ( "+courseCode.get(5)+" )                                        "+" (7) ");    
                        doc.add(p11);
                    }
                    doc.close();
                    JOptionPane.showMessageDialog(null, "Admit No DIU-"+generatedKey);
                    Desktop.getDesktop().open(new java.io.File(location+"Admit of DIU "+generatedKey+".pdf"));
            
                 }
            catch(Exception ec){
                Logger.getLogger(AdmitCard.class.getName()).log(Level.SEVERE, null, ec);
               
            }  
        
 }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmitCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmitCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmitCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmitCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmitCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PrintBtn;
    private javax.swing.JTextField batchTf;
    private javax.swing.JButton closebtn;
    private javax.swing.JTextField fathersNameTf;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mothersNameTf;
    private javax.swing.JTextField rollTf;
    private javax.swing.JTextField semesterTf;
    private javax.swing.JTextField studentNameTf;
    // End of variables declaration//GEN-END:variables
}
