/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diu.desk;

import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Scanner;
import javax.swing.JOptionPane;

 
public class AdminProfileUpdate extends javax.swing.JFrame {
        
    String user_name;
     Connection con = null;
     Statement statement = null;
     PreparedStatement pStatement = null;
     ResultSet rs = null;
    String saltCode;
     String mySecurePass;
      String password1="";
      String currentpass;
      String currentsalt;
      String password2="";
    /**
     * Creates new form AdminProfileUpdate
     */
    public AdminProfileUpdate() {
        initComponents();
         con = ConnectionFactory.getMysqlConnection();
         ReadUserName();
         CheckUserInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        designationTf = new javax.swing.JTextField();
        nameTf = new javax.swing.JTextField();
        mobileTf = new javax.swing.JTextField();
        userNameTf = new javax.swing.JTextField();
        emailTf = new javax.swing.JTextField();
        confirmPassTf = new javax.swing.JPasswordField();
        passwordTf = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        Savebtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        currentPassTf = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin's Profile Information Update");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 69, 79));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Designation:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 80, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 60, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Login ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 60, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Confirm Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 120, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mobile");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 60, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 60, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Change Password: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 120, 30));

        designationTf.setEditable(false);
        jPanel1.add(designationTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 190, 30));
        jPanel1.add(nameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 190, 30));
        jPanel1.add(mobileTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 190, 30));
        jPanel1.add(userNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 190, 30));
        jPanel1.add(emailTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 190, 30));

        confirmPassTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmPassTfFocusGained(evt);
            }
        });
        jPanel1.add(confirmPassTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 190, 30));

        passwordTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTfFocusGained(evt);
            }
        });
        jPanel1.add(passwordTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 190, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit account_26px.png"))); // NOI18N
        jLabel8.setText("Update Profile Information");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 680, 40));

        Savebtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Savebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save_26px.png"))); // NOI18N
        Savebtn.setText("Save");
        Savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebtnActionPerformed(evt);
            }
        });
        jPanel1.add(Savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 130, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Current Password: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 120, 30));

        currentPassTf.setText("jPasswordField1");
        currentPassTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                currentPassTfFocusGained(evt);
            }
        });
        jPanel1.add(currentPassTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 190, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebtnActionPerformed
       String password = new String(currentPassTf.getPassword());
       
      password1=new String(passwordTf.getPassword());
      password2=new String(confirmPassTf.getPassword());
       
            
       CheckCurrentPassword();
       
        boolean passwordMatch=PasswordManager.verifyUserPassword(password,currentpass,currentsalt);
                 if(passwordMatch){
                      if(password1.equals("") || password2.equals("")){
                            UpdateWithoutPass();
                        } 
                      else{
                     UpdateUserInfo();
                      }
                   }
                 else{
                     JOptionPane.showMessageDialog(null, "Check your Current Password");
                 }
       
    }//GEN-LAST:event_SavebtnActionPerformed

    private void passwordTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTfFocusGained
        passwordTf.setText("");
    }//GEN-LAST:event_passwordTfFocusGained

    private void confirmPassTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPassTfFocusGained
      confirmPassTf.setText("");
    }//GEN-LAST:event_confirmPassTfFocusGained

    private void currentPassTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_currentPassTfFocusGained
        currentPassTf.setText("");
    }//GEN-LAST:event_currentPassTfFocusGained
    
    public void UpdateUserInfo(){
        try{ 
//       password1=new String(passwordTf.getPassword());
//      password2=new String(confirmPassTf.getPassword());
            generatepassword();
             if(password1.matches(password2)){
                
                pStatement=con.prepareStatement("UPDATE adminlogin SET password=?,salt_value=?,mobile=?,userName=?,name=? WHERE email=?");
                pStatement.setString(1,mySecurePass);
                pStatement.setString(2,saltCode);
                pStatement.setString(3,mobileTf.getText());
                pStatement.setString(4,userNameTf.getText());
                pStatement.setString(5,nameTf.getText());
                pStatement.setString(6,emailTf.getText());
                pStatement.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Your Information & Password is Updated\nPlease Log in with your new password now");
                this.dispose();
                Login h=new Login();
                h.setVisible(true);
       }
             else{
                    JOptionPane.showMessageDialog(null,"Passward missmatch" );

               }
    }
            catch(Exception exc){
                System.out.println(exc);
            }
                
    }
    
     public void UpdateWithoutPass(){
        try{ 
           
                pStatement=con.prepareStatement("UPDATE adminlogin SET mobile=?,userName=?,name=? WHERE email=?");
                pStatement.setString(1,mobileTf.getText());
                pStatement.setString(2,userNameTf.getText());
                pStatement.setString(3,nameTf.getText());
                pStatement.setString(4,emailTf.getText());
                pStatement.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Your Information is Updated.");
                this.dispose();
                     }    
            catch(Exception exc){
                System.out.println(exc);
            }
                
    }
    
    
    
    public void CheckCurrentPassword(){
    
        try{
             String usercheck="SELECT password,salt_value FROM adminlogin WHERE userName=? ";
             pStatement=con.prepareStatement(usercheck);

                 pStatement.setString(1,userNameTf.getText());
                  rs=pStatement.executeQuery();

             if(rs.next()){
              currentpass=rs.getString("password");
              currentsalt=rs.getString("salt_value");
                
             }
        }
             catch(Exception ex){
                     JOptionPane.showMessageDialog(null, "Error: "+ex);
                     }
    
    }
    
    
    
    public void generatepassword(){
         
        // Generate Salt. The generated value can be stored in DB. 
        saltCode = PasswordManager.getSalt(30);        
        // Protect user's password. The generated value can be stored in DB.
        mySecurePass = PasswordManager.generateSecurePassword(password1, saltCode);
       
    }
    public void CheckUserInfo(){
         try{
           
       pStatement=con.prepareStatement("SELECT * FROM `adminlogin` WHERE  userName=?");
        pStatement.setString(1,user_name);
           rs=pStatement.executeQuery();
           if(rs.next()){
                 nameTf.setText(rs.getString("name"));
                 userNameTf.setText(rs.getString("userName"));
                 designationTf.setText(rs.getString("designation"));
                 emailTf.setText(rs.getString("email"));
                 mobileTf.setText(rs.getString("mobile"));
               
           }
       }
       catch(Exception ex){
           System.out.println("Error"+ex);
       }
    }
    
    public void ReadUserName(){
        File file=new File("user_name.txt");
        try{
            Scanner input=new Scanner(file);
            user_name=input.nextLine();
            System.out.println(user_name);
        }catch(Exception ec){
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminProfileUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminProfileUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminProfileUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminProfileUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminProfileUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Savebtn;
    private javax.swing.JPasswordField confirmPassTf;
    private javax.swing.JPasswordField currentPassTf;
    private javax.swing.JTextField designationTf;
    private javax.swing.JTextField emailTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mobileTf;
    private javax.swing.JTextField nameTf;
    private javax.swing.JPasswordField passwordTf;
    private javax.swing.JTextField userNameTf;
    // End of variables declaration//GEN-END:variables
}
