/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diu.desk;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
 
public class calendar extends javax.swing.JFrame {
    String Role="";
 Connection con = ConnectionFactory.getMysqlConnection();
     Statement statement = null;
     PreparedStatement pStatement = null;
     ResultSet rs = null;
     
     String[] title = new String[11]; 
             String[] date = new String[11];
              int i=1;
    /**
     * Creates new form todoList
     */
              public calendar(String role, String home) {
        this.Role=role;
        initComponents();
        next.setVisible(false);
        edit.setVisible(false);
        save.setVisible(false);
        homebtn.setVisible(false);
          try {
             
           pStatement=con.prepareStatement("SELECT * FROM academiccalendar");
           rs=pStatement.executeQuery();
           
           while(rs.next()){
            title[i]=rs.getString("title");
            date[i]=rs.getString("date");            
             i++;
           }
            
              title1.setText(title[1]);
             title2.setText(title[2]);
             title3.setText(title[3]);
             title4.setText(title[4]);
             title5.setText(title[5]);
             title6.setText(title[6]);
             title7.setText(title[7]);
             title8.setText(title[8]);
             title9.setText(title[9]);
             title10.setText(title[10]);
             
             date1.setText(date[1]);
             date2.setText(date[2]);
             date3.setText(date[3]);
             date4.setText(date[4]);
             date5.setText(date[5]);
             date6.setText(date[6]);
             date7.setText(date[7]);
             date8.setText(date[8]);
             date9.setText(date[9]);
             date10.setText(date[10]);
             
          
          
    }catch(Exception rs){
        System.out.println("Error"+rs);
       }
        
        
    }
              
    public calendar(String role) {
        this.Role=role;
        initComponents();
        closebtn.setVisible(false);
         try {
             
           pStatement=con.prepareStatement("SELECT * FROM academiccalendar");
           rs=pStatement.executeQuery();
           
           while(rs.next()){
            title[i]=rs.getString("title");
            date[i]=rs.getString("date");            
             i++;
           }
            
             title1.setText(title[1]);
             title2.setText(title[2]);
             title3.setText(title[3]);
             title4.setText(title[4]);
             title5.setText(title[5]);
             title6.setText(title[6]);
             title7.setText(title[7]);
             title8.setText(title[8]);
             title9.setText(title[9]);
             title10.setText(title[10]);
             
             date1.setText(date[1]);
             date2.setText(date[2]);
             date3.setText(date[3]);
             date4.setText(date[4]);
             date5.setText(date[5]);
             date6.setText(date[6]);
             date7.setText(date[7]);
             date8.setText(date[8]);
             date9.setText(date[9]);
             date10.setText(date[10]);
             
          
          
    }catch(Exception rs){
        System.out.println("Error"+rs);
       }
        
        
    }

    private calendar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        date1 = new javax.swing.JTextField();
        title1 = new javax.swing.JTextField();
        title2 = new javax.swing.JTextField();
        date2 = new javax.swing.JTextField();
        title3 = new javax.swing.JTextField();
        date3 = new javax.swing.JTextField();
        title4 = new javax.swing.JTextField();
        date4 = new javax.swing.JTextField();
        title5 = new javax.swing.JTextField();
        date5 = new javax.swing.JTextField();
        date6 = new javax.swing.JTextField();
        title6 = new javax.swing.JTextField();
        title7 = new javax.swing.JTextField();
        date7 = new javax.swing.JTextField();
        date10 = new javax.swing.JTextField();
        title10 = new javax.swing.JTextField();
        title9 = new javax.swing.JTextField();
        date9 = new javax.swing.JTextField();
        date8 = new javax.swing.JTextField();
        title8 = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        save = new javax.swing.JButton();
        homebtn = new javax.swing.JButton();
        next = new javax.swing.JButton();
        closebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Academic Calendar");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 69, 79));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar_40px.png"))); // NOI18N
        jLabel1.setText("Academic Calendar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 680, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ac-exam.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 30, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ac-classroom_20px.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 30, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ac-result.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 30, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ac-tution.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 30, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ac-close.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 30, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ac-final exam.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 30, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ac-exam.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 30, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ac-result.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 30, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ac-classroom_20px.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 30, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ac-exam.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 30, 30));

        date1.setEditable(false);
        date1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 170, 28));

        title1.setEditable(false);
        title1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        title1.setMargin(new java.awt.Insets(1, 26, 1, 1));
        jPanel1.add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 310, 28));

        title2.setEditable(false);
        title2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        title2.setMargin(new java.awt.Insets(1, 26, 1, 1));
        jPanel1.add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 310, 28));

        date2.setEditable(false);
        date2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 170, 28));

        title3.setEditable(false);
        title3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        title3.setMargin(new java.awt.Insets(1, 26, 1, 1));
        jPanel1.add(title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 310, 28));

        date3.setEditable(false);
        date3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(date3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 170, 28));

        title4.setEditable(false);
        title4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        title4.setMargin(new java.awt.Insets(1, 26, 1, 1));
        jPanel1.add(title4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 310, 28));

        date4.setEditable(false);
        date4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(date4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 170, 28));

        title5.setEditable(false);
        title5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        title5.setMargin(new java.awt.Insets(1, 26, 1, 1));
        jPanel1.add(title5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 310, 28));

        date5.setEditable(false);
        date5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(date5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 170, 28));

        date6.setEditable(false);
        date6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(date6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 170, 28));

        title6.setEditable(false);
        title6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        title6.setMargin(new java.awt.Insets(1, 26, 1, 1));
        jPanel1.add(title6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 310, 28));

        title7.setEditable(false);
        title7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        title7.setMargin(new java.awt.Insets(1, 26, 1, 1));
        jPanel1.add(title7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 310, 28));

        date7.setEditable(false);
        date7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(date7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 170, 28));

        date10.setEditable(false);
        date10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(date10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 170, 28));

        title10.setEditable(false);
        title10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        title10.setMargin(new java.awt.Insets(1, 26, 1, 1));
        jPanel1.add(title10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 310, 28));

        title9.setEditable(false);
        title9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        title9.setMargin(new java.awt.Insets(1, 26, 1, 1));
        jPanel1.add(title9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 310, 28));

        date9.setEditable(false);
        date9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(date9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 170, 28));

        date8.setEditable(false);
        date8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(date8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 170, 28));

        title8.setEditable(false);
        title8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        title8.setMargin(new java.awt.Insets(1, 26, 1, 1));
        jPanel1.add(title8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 310, 28));

        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_26px.png"))); // NOI18N
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 100, 30));

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save_26px.png"))); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 100, 30));

        homebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_26px.png"))); // NOI18N
        homebtn.setText("Home");
        homebtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        jPanel1.add(homebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 110, 30));

        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next-26px.png"))); // NOI18N
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 100, 30));

        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_26px.png"))); // NOI18N
        closebtn.setText("Close");
        closebtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        jPanel1.add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
       date1.setEditable(true); 
       date2.setEditable(true);
       date3.setEditable(true);
       date4.setEditable(true);
       date5.setEditable(true);
       date6.setEditable(true);
       date7.setEditable(true);
       date8.setEditable(true);
       date9.setEditable(true);
       date10.setEditable(true);      
       
    }//GEN-LAST:event_editActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        // TODO add your handling code here:
        Home hm=new Home(Role);
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homebtnActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        NewRoutine n=new NewRoutine(Role);
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nextActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
         this.dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
       try {
String sql1 = "UPDATE academiccalendar SET date=? WHERE id='1'";
pStatement=con.prepareStatement(sql1);
pStatement.setString(1, date1.getText());
pStatement.execute();

String sql2 = "UPDATE academiccalendar SET date=? WHERE id='2'";
pStatement=con.prepareStatement(sql2);
pStatement.setString(1, date2.getText());
pStatement.execute();

String sql3 = "UPDATE academiccalendar SET date=? WHERE id='3'";
pStatement=con.prepareStatement(sql3);
pStatement.setString(1, date3.getText());
pStatement.execute();

String sql4 = "UPDATE academiccalendar SET date=? WHERE id='4'";
pStatement=con.prepareStatement(sql4);
pStatement.setString(1, date4.getText());
pStatement.execute();

String sql5 = "UPDATE academiccalendar SET date=? WHERE id='5'";
pStatement=con.prepareStatement(sql5);
pStatement.setString(1, date5.getText());
pStatement.execute();

String sql6 = "UPDATE academiccalendar SET date=? WHERE id='6'";
pStatement=con.prepareStatement(sql6);
pStatement.setString(1, date6.getText());
pStatement.execute();

String sql7 = "UPDATE academiccalendar SET date=? WHERE id='7'";
pStatement=con.prepareStatement(sql7);
pStatement.setString(1, date7.getText());
pStatement.execute();

String sql10 = "UPDATE academiccalendar SET date=? WHERE id='8'";
pStatement=con.prepareStatement(sql10);
pStatement.setString(1, date8.getText());
pStatement.execute();

String sql8 = "UPDATE academiccalendar SET date=? WHERE id='9'";
pStatement=con.prepareStatement(sql8);
pStatement.setString(1, date9.getText());
pStatement.execute();

String sql9 = "UPDATE academiccalendar SET date=? WHERE id='10'";
pStatement=con.prepareStatement(sql9);
pStatement.setString(1, date10.getText());
pStatement.execute();



JOptionPane.showMessageDialog(null, "Success !");




        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calendar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closebtn;
    private javax.swing.JTextField date1;
    private javax.swing.JTextField date10;
    private javax.swing.JTextField date2;
    private javax.swing.JTextField date3;
    private javax.swing.JTextField date4;
    private javax.swing.JTextField date5;
    private javax.swing.JTextField date6;
    private javax.swing.JTextField date7;
    private javax.swing.JTextField date8;
    private javax.swing.JTextField date9;
    private javax.swing.JButton edit;
    private javax.swing.JButton homebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton next;
    private javax.swing.JButton save;
    private javax.swing.JTextField title1;
    private javax.swing.JTextField title10;
    private javax.swing.JTextField title2;
    private javax.swing.JTextField title3;
    private javax.swing.JTextField title4;
    private javax.swing.JTextField title5;
    private javax.swing.JTextField title6;
    private javax.swing.JTextField title7;
    private javax.swing.JTextField title8;
    private javax.swing.JTextField title9;
    // End of variables declaration//GEN-END:variables
}
