/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diu.desk;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
 
public class ForgetPassword extends javax.swing.JFrame {
    Connection con = null;
     Statement statement = null;
     PreparedStatement pStatement = null;
     ResultSet rs = null;
     PasswordRecover passrec=new PasswordRecover();
     SetPassword sp=new SetPassword();
     
    /**
     * Creates new form ForgetPassword
     */
    public ForgetPassword() {
        initComponents();
        con = ConnectionFactory.getMysqlConnection();
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codeSendpan = new javax.swing.JPanel();
        UserName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SendCode = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forget Password");
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        codeSendpan.setBackground(new java.awt.Color(0, 69, 79));
        codeSendpan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        codeSendpan.add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 170, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        codeSendpan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 91, 30));

        SendCode.setText("Request for code");
        SendCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendCodeActionPerformed(evt);
            }
        });
        codeSendpan.add(SendCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 180, 40));

        getContentPane().add(codeSendpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 220));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
// <editor-fold defaultstate="collapsed" desc="Email Send Button action">
    private void SendCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendCodeActionPerformed
               
                try{
                             pStatement=con.prepareStatement("SELECT email from adminlogin WHERE userName=?");
                             pStatement.setString(1,UserName.getText());
                             rs=pStatement.executeQuery();
                              while(rs.next()){
                               String email=rs.getString("email");
                              sp.receiverMail=email;
                              passrec.receiverEmail=email;
                              passrec.SendEmail();
                                  }
                }
                catch(Exception excp){
                    System.out.println(excp+"Error on send ");
                }
      
        
          try{    
                        pStatement=con.prepareStatement("UPDATE adminlogin SET recover_code=? WHERE userName=?");
                        pStatement.setString(1,passrec.generatedCode);
                        pStatement.setString(2,UserName.getText());
                        pStatement.executeUpdate();
                        
                       sp.showText.setText("A code is sent in your Email");
                       
                        sp.setVisible(true);
                        this.setVisible(false);
                        
                       
                    }
          catch(Exception exc){
              System.out.println(exc);
          }
    }//GEN-LAST:event_SendCodeActionPerformed
//</editor-fold> 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SendCode;
    private javax.swing.JTextField UserName;
    private javax.swing.JPanel codeSendpan;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
