/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diu.desk;

import Library.LibararyManagement;
import com.sbix.jnotify.NPosition;
import com.sbix.jnotify.NoticeWindow;
import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.nio.CharBuffer;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

 
public class Home extends javax.swing.JFrame implements Runnable{
  
       Connection con = null;
     Statement statement = null;
     PreparedStatement pStatement = null;
     ResultSet rs = null;
     String Role="";
    
      int hour,second,minute;
     int day,month,year;
     String timestr,yearstr;
     
    public Home() {
      
    }

    public Home(String role)
    {
       
        
     Thread thread=new Thread(this);
     thread.start();
        initComponents();
       con = ConnectionFactory.getMysqlConnection();       
       jPanel1.setVisible(true);       
       AcademicCalanderPanel.setVisible(false);
       this.Role=role;
       CheckUserRole(Role);
    }
    private void CheckUserRole(String role) {
        
      if(role.equals("developer"))
        {
            CourseDistributionBtn.setEnabled(true);
            ClassRoutineBtn.setEnabled(true);
            TeachersLoadBtn.setEnabled(true);
            LibraryManagementBtn.setEnabled(true);
            admitbtn.setEnabled(true);
            StudentInfo.setEnabled(true);
            TeachersInfo.setEnabled(true);
            todo.setEnabled(true);
            routine.setEnabled(true);
            addTeacher.setEnabled(true);
            removeTeacher.setEnabled(true);
            about.setEnabled(true);
            AcamadicCalanderBtn.setEnabled(true);
            editaccountinfo.setEnabled(true);
            manual.setEnabled(true);
        }
        
      else if(role.equals("chairman"))
        {
            CourseDistributionBtn.setEnabled(true);
            ClassRoutineBtn.setEnabled(true);
            TeachersLoadBtn.setEnabled(true);
            LibraryManagementBtn.setEnabled(true);
           
        }
        else if(role.equals("dean"))
        {
            CourseDistributionBtn.setEnabled(true);
            ClassRoutineBtn.setEnabled(true);
            TeachersLoadBtn.setEnabled(true);
            
        }
        else if(role.equals("aregistrar"))
        {
            ClassRoutineBtn.setEnabled(true);
        }
         else if(role.equals("accounts"))
        {
            admitbtn.setEnabled(true);
        }
        
         else if(role.equals("librarian"))
        {
            LibraryManagementBtn.setEnabled(true);
            
        }
    }

    private static void openWebpage(String urlString) {
    try {
        Desktop.getDesktop().browse(new URL(urlString).toURI());
    } catch (Exception e) {
        e.printStackTrace();
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CourseDistributionL = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TeachersLoadL = new javax.swing.JLabel();
        ClassRoutineL = new javax.swing.JLabel();
        CourseDistributionBtn = new javax.swing.JButton();
        LibraryManagementBtn = new javax.swing.JButton();
        TeachersLoadBtn = new javax.swing.JButton();
        ClassRoutineBtn = new javax.swing.JButton();
        adminMessageBtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        manual = new javax.swing.JButton();
        AcamadicCalanderBtn = new javax.swing.JButton();
        editaccountinfo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        NameLbl = new javax.swing.JLabel();
        YearShow = new javax.swing.JLabel();
        admitbtn = new javax.swing.JButton();
        ClockShow = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        StudentInfo = new javax.swing.JButton();
        TeachersInfo = new javax.swing.JButton();
        todo = new javax.swing.JButton();
        ClassRoutineL1 = new javax.swing.JLabel();
        TeachersLoadL1 = new javax.swing.JLabel();
        CourseDistributionL1 = new javax.swing.JLabel();
        about = new javax.swing.JButton();
        routine = new javax.swing.JButton();
        addTeacher = new javax.swing.JButton();
        removeTeacher = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AcademicCalanderPanel = new javax.swing.JPanel();
        adScroolPan = new javax.swing.JScrollPane();
        AcademicData = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart University System | Home");
        setSize(new java.awt.Dimension(100, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 69, 79));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DHAKA INTERNATIONAL UNIVERSITY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 880, 110));

        CourseDistributionL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/timetable_120px.png"))); // NOI18N
        jPanel1.add(CourseDistributionL, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 130, 140));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DIU-LOGO-small.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 150, 160));

        TeachersLoadL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admit.png"))); // NOI18N
        jPanel1.add(TeachersLoadL, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 130, 140));

        ClassRoutineL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/books_120px.png"))); // NOI18N
        jPanel1.add(ClassRoutineL, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 140, 130, 140));

        CourseDistributionBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CourseDistributionBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cd_26px.png"))); // NOI18N
        CourseDistributionBtn.setText("Course Distribution");
        CourseDistributionBtn.setToolTipText("View Current Course Distribution");
        CourseDistributionBtn.setEnabled(false);
        CourseDistributionBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CourseDistributionBtn.setMargin(new java.awt.Insets(1, 1, 1, 0));
        CourseDistributionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseDistributionBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CourseDistributionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 290, 200, 30));

        LibraryManagementBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        LibraryManagementBtn.setText("Library");
        LibraryManagementBtn.setEnabled(false);
        LibraryManagementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibraryManagementBtnActionPerformed(evt);
            }
        });
        jPanel1.add(LibraryManagementBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, 180, 40));

        TeachersLoadBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TeachersLoadBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tl-26px.png"))); // NOI18N
        TeachersLoadBtn.setText("Teachers Load");
        TeachersLoadBtn.setToolTipText("Download Current Teachers' Load");
        TeachersLoadBtn.setEnabled(false);
        TeachersLoadBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TeachersLoadBtn.setMargin(new java.awt.Insets(1, 1, 1, 0));
        TeachersLoadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeachersLoadBtnActionPerformed(evt);
            }
        });
        jPanel1.add(TeachersLoadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 330, 200, 30));

        ClassRoutineBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ClassRoutineBtn.setText("Class Routine");
        ClassRoutineBtn.setEnabled(false);
        ClassRoutineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassRoutineBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ClassRoutineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 180, 40));

        adminMessageBtn.setBackground(new java.awt.Color(204, 204, 204));
        adminMessageBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        adminMessageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sms_26px.png"))); // NOI18N
        adminMessageBtn.setText("Admin's Message");
        adminMessageBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        adminMessageBtn.setIconTextGap(5);
        adminMessageBtn.setMargin(new java.awt.Insets(1, 1, 1, 0));
        adminMessageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminMessageBtnActionPerformed(evt);
            }
        });
        jPanel1.add(adminMessageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 170, 40));

        logoutbtn.setBackground(new java.awt.Color(204, 204, 204));
        logoutbtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout_rounded_up_filled_26px.png"))); // NOI18N
        logoutbtn.setText("Log Out");
        logoutbtn.setMargin(new java.awt.Insets(1, 1, 1, 0));
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        jPanel1.add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 170, 60));

        manual.setBackground(new java.awt.Color(204, 204, 204));
        manual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        manual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_manual_26px.png"))); // NOI18N
        manual.setText("User Manual");
        manual.setToolTipText("");
        manual.setAlignmentY(0.0F);
        manual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manual.setMargin(new java.awt.Insets(1, 1, 1, 0));
        manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualActionPerformed(evt);
            }
        });
        jPanel1.add(manual, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 170, 40));

        AcamadicCalanderBtn.setBackground(new java.awt.Color(204, 204, 204));
        AcamadicCalanderBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AcamadicCalanderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar_26px.png"))); // NOI18N
        AcamadicCalanderBtn.setText("Academic Calander");
        AcamadicCalanderBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AcamadicCalanderBtn.setIconTextGap(5);
        AcamadicCalanderBtn.setMargin(new java.awt.Insets(1, 1, 1, 0));
        AcamadicCalanderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcamadicCalanderBtnActionPerformed(evt);
            }
        });
        jPanel1.add(AcamadicCalanderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 170, 40));

        editaccountinfo.setBackground(new java.awt.Color(204, 204, 204));
        editaccountinfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        editaccountinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit account_26px.png"))); // NOI18N
        editaccountinfo.setText("Edit Account Info");
        editaccountinfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        editaccountinfo.setIconTextGap(5);
        editaccountinfo.setMargin(new java.awt.Insets(1, 1, 1, 0));
        editaccountinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editaccountinfoActionPerformed(evt);
            }
        });
        jPanel1.add(editaccountinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 170, 40));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Smart University System ©  2019  |  Version: 1.0  ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 730, 30));

        NameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NameLbl.setForeground(new java.awt.Color(255, 255, 255));
        NameLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.png"))); // NOI18N
        jPanel1.add(NameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 160, 200, 50));

        YearShow.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        YearShow.setForeground(new java.awt.Color(255, 255, 255));
        YearShow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(YearShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 170, 30));

        admitbtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        admitbtn.setText("Admit Card");
        admitbtn.setEnabled(false);
        admitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(admitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 180, 40));

        ClockShow.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ClockShow.setForeground(new java.awt.Color(255, 255, 255));
        ClockShow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(ClockShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 170, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/external_link_30px.png"))); // NOI18N
        jButton4.setText("Quick Links");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 240, 200, 40));

        StudentInfo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        StudentInfo.setText("Students Info");
        StudentInfo.setEnabled(false);
        StudentInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentInfoActionPerformed(evt);
            }
        });
        jPanel1.add(StudentInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 180, 40));

        TeachersInfo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        TeachersInfo.setText("Teachers Info");
        TeachersInfo.setEnabled(false);
        TeachersInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeachersInfoActionPerformed(evt);
            }
        });
        jPanel1.add(TeachersInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 180, 40));

        todo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        todo.setText("To Do List");
        todo.setEnabled(false);
        todo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todoActionPerformed(evt);
            }
        });
        jPanel1.add(todo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 180, 40));

        ClassRoutineL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/todo_list_120px.png"))); // NOI18N
        jPanel1.add(ClassRoutineL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, 130, 140));

        TeachersLoadL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/teacher.png"))); // NOI18N
        jPanel1.add(TeachersLoadL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 130, 140));

        CourseDistributionL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/students_120px.png"))); // NOI18N
        jPanel1.add(CourseDistributionL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 130, 140));

        about.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about_26px.png"))); // NOI18N
        about.setText("About us");
        about.setToolTipText("");
        about.setEnabled(false);
        about.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        about.setMargin(new java.awt.Insets(1, 1, 1, 0));
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        jPanel1.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 490, 200, 30));

        routine.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        routine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/routine-sm-grn-26px.png"))); // NOI18N
        routine.setText("Current Routine");
        routine.setToolTipText("Download Current Class Routine");
        routine.setEnabled(false);
        routine.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        routine.setMargin(new java.awt.Insets(1, 1, 1, 0));
        routine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routineActionPerformed(evt);
            }
        });
        jPanel1.add(routine, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 370, 200, 30));

        addTeacher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_user_mhtale_26px.png"))); // NOI18N
        addTeacher.setText("Add New Teacher");
        addTeacher.setToolTipText("");
        addTeacher.setEnabled(false);
        addTeacher.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addTeacher.setMargin(new java.awt.Insets(1, 1, 1, 0));
        addTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeacherActionPerformed(evt);
            }
        });
        jPanel1.add(addTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 410, 200, 30));

        removeTeacher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removeTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove_user_male_26px.png"))); // NOI18N
        removeTeacher.setText("Remove a Teacher");
        removeTeacher.setToolTipText("");
        removeTeacher.setEnabled(false);
        removeTeacher.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        removeTeacher.setMargin(new java.awt.Insets(1, 1, 1, 0));
        removeTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTeacherActionPerformed(evt);
            }
        });
        jPanel1.add(removeTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 450, 200, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Facebook_26px.png"))); // NOI18N
        jLabel2.setToolTipText("Visit Official FB Group of DIU-CSE");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 30, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/web_26px.png"))); // NOI18N
        jLabel6.setToolTipText("Visit www.diu.ac");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 30, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/email-_26px.png"))); // NOI18N
        jLabel7.setToolTipText("Login to Official Mailbox of DIU");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 30, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 600));

        AcademicCalanderPanel.setBackground(new java.awt.Color(153, 153, 255));
        AcademicCalanderPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adScroolPan.setForeground(javax.swing.UIManager.getDefaults().getColor("textHighlightText"));
        adScroolPan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        AcademicData.setEditable(false);
        AcademicData.setColumns(20);
        AcademicData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AcademicData.setForeground(java.awt.Color.white);
        AcademicData.setLineWrap(true);
        AcademicData.setRows(5);
        AcademicData.setWrapStyleWord(true);
        AcademicData.setAlignmentX(50.0F);
        AcademicData.setAlignmentY(50.0F);
        AcademicData.setBorder(null);
        AcademicData.setCaretColor(new java.awt.Color(255, 255, 255));
        AcademicData.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AcademicData.setOpaque(false);
        adScroolPan.setViewportView(AcademicData);

        AcademicCalanderPanel.add(adScroolPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 560, 240));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/acd.jpg"))); // NOI18N
        AcademicCalanderPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 350));

        getContentPane().add(AcademicCalanderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LibraryManagementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibraryManagementBtnActionPerformed
        LibararyManagement lm=new LibararyManagement();
        lm.setVisible(true);
    }//GEN-LAST:event_LibraryManagementBtnActionPerformed

    private void CourseDistributionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseDistributionBtnActionPerformed
       
       CourseDistribution csdistribution = new CourseDistribution(Role);
       csdistribution.setVisible(true);
       this.dispose();
      
    }//GEN-LAST:event_CourseDistributionBtnActionPerformed

    private void TeachersLoadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeachersLoadBtnActionPerformed
        // TODO add your handling code here:
         RoutineGen rg=new RoutineGen(Role);
        rg.ExportTL();
        
    }//GEN-LAST:event_TeachersLoadBtnActionPerformed

    private void ClassRoutineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassRoutineBtnActionPerformed
        RoutineGen rg = new RoutineGen(Role);
        rg.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_ClassRoutineBtnActionPerformed

    private void adminMessageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminMessageBtnActionPerformed
        MailBox sendEmail=new MailBox();
        sendEmail.setVisible(true);
        
        
    }//GEN-LAST:event_adminMessageBtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        Login login=new Login();
        login.setVisible(true);
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void admitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admitbtnActionPerformed
        // TODO add your handling code here:
        AdmitCard acard=new AdmitCard();
        acard.setVisible(true);
        
    }//GEN-LAST:event_admitbtnActionPerformed

    private void AcamadicCalanderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcamadicCalanderBtnActionPerformed
         
         calendar cd=new calendar(Role,"home");
         cd.setVisible(true);
         
         //this.dispose();
         
    }//GEN-LAST:event_AcamadicCalanderBtnActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        AcademicCalanderPanel.setVisible(false);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void StudentInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentInfoActionPerformed
       StudentCenter sc= new StudentCenter();
       sc.setVisible(true);
    }//GEN-LAST:event_StudentInfoActionPerformed

    private void TeachersInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeachersInfoActionPerformed
        TeachersCenter tc= new TeachersCenter();
         tc.setVisible(true);
    }//GEN-LAST:event_TeachersInfoActionPerformed

    private void todoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todoActionPerformed
        todoList todo= new todoList();
         todo.setVisible(true);
    }//GEN-LAST:event_todoActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
        AboutUS ab=new AboutUS();
        ab.setVisible(true);
    }//GEN-LAST:event_aboutActionPerformed

    private void routineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routineActionPerformed
        // TODO add your handling code here:
        GenRoutine rg=new GenRoutine();
           try {
               rg.RoutineGen();
           } catch (IOException ex) {
               Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
           }
    }//GEN-LAST:event_routineActionPerformed

    private void addTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeacherActionPerformed
       TeachersCenter tc=new TeachersCenter("add");
       tc.setVisible(true);
    }//GEN-LAST:event_addTeacherActionPerformed

    private void removeTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTeacherActionPerformed
         TeachersCenter tc=new TeachersCenter("add","Remove");
       tc.setVisible(true);
    }//GEN-LAST:event_removeTeacherActionPerformed

    private void editaccountinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editaccountinfoActionPerformed
      AdminProfileUpdate apu=new AdminProfileUpdate();
      apu.setVisible(true);
    }//GEN-LAST:event_editaccountinfoActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        openWebpage("http://www.diu.ac");
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        openWebpage("https://mail.diu-bd.net/webmail/");
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       openWebpage(" https://www.facebook.com/groups/1726307134294635/"); 
    }//GEN-LAST:event_jLabel2MouseClicked

    private void manualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualActionPerformed
        // TODO add your handling code here:
        File file=new File("users-manual.pdf");
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+file);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error! PDF not Found!");
        }
    }//GEN-LAST:event_manualActionPerformed

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AcademicCalanderPanel;
    private javax.swing.JTextArea AcademicData;
    private javax.swing.JButton AcamadicCalanderBtn;
    private javax.swing.JButton ClassRoutineBtn;
    private javax.swing.JLabel ClassRoutineL;
    private javax.swing.JLabel ClassRoutineL1;
    private javax.swing.JLabel ClockShow;
    private javax.swing.JButton CourseDistributionBtn;
    private javax.swing.JLabel CourseDistributionL;
    private javax.swing.JLabel CourseDistributionL1;
    private javax.swing.JButton LibraryManagementBtn;
    public javax.swing.JLabel NameLbl;
    private javax.swing.JButton StudentInfo;
    private javax.swing.JButton TeachersInfo;
    private javax.swing.JButton TeachersLoadBtn;
    private javax.swing.JLabel TeachersLoadL;
    private javax.swing.JLabel TeachersLoadL1;
    private javax.swing.JLabel YearShow;
    private javax.swing.JButton about;
    private javax.swing.JScrollPane adScroolPan;
    private javax.swing.JButton addTeacher;
    private javax.swing.JButton adminMessageBtn;
    private javax.swing.JButton admitbtn;
    private javax.swing.JButton editaccountinfo;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton manual;
    private javax.swing.JButton removeTeacher;
    private javax.swing.JButton routine;
    private javax.swing.JButton todo;
    // End of variables declaration//GEN-END:variables

      @Override
    public void run() {
         while(true){
           try{
               Calendar cal = Calendar.getInstance();
               hour=cal.get(Calendar.HOUR_OF_DAY);
               if(hour>12)
                   hour=hour-12;
               minute=cal.get(Calendar.MINUTE);
               second=cal.get(Calendar.SECOND);
               year=cal.get(Calendar.YEAR);
               day=cal.get(Calendar.DAY_OF_MONTH);
               SimpleDateFormat sdf=new SimpleDateFormat("hh:mm:ss a");
               SimpleDateFormat df=new SimpleDateFormat("dd.MM.yyyy");
               Date date=cal.getTime();
               timestr=sdf.format(date);
               yearstr=df.format(date);
                ClockShow.setText(timestr);
             YearShow.setText(yearstr);
               
           }catch(Exception e){
             
           }
    }

    } 
}
