/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diu.desk;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

 
public class SetPassword extends javax.swing.JFrame {
Connection con = null;
     Statement statement = null;
     PreparedStatement pStatement = null;
     ResultSet rs = null;
     PasswordRecover passrec=new PasswordRecover();
     String recode;
     String saltCode;
     String mySecurePass;
     String password1;
     String password2;
     String receiverMail;
    /**
     * Creates new form SetPassword
     */
    public SetPassword() {
        initComponents();
        pass.setEditable(false);
        cpass.setEditable(false);
        con = ConnectionFactory.getMysqlConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        codeTf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        cpass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        showText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change Password");
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 69, 79));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        saveBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveBtn.setText("Update Password");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 168, 33));

        codeTf.setToolTipText("Enter Your Code That receive by email");
        codeTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeTfActionPerformed(evt);
            }
        });
        codeTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codeTfKeyReleased(evt);
            }
        });
        jPanel1.add(codeTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 160, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Code");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 90, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 94, 29));

        pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass.setText("jPasswordField1");
        pass.setToolTipText("password might > 4");
        pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFocusGained(evt);
            }
        });
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 160, 30));

        cpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpass.setText("jPasswordField1");
        cpass.setToolTipText("password might > 4");
        cpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cpassFocusGained(evt);
            }
        });
        jPanel1.add(cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 160, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirm Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 130, 31));

        showText.setForeground(new java.awt.Color(0, 153, 51));
        jPanel1.add(showText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 240, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void codeTfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeTfKeyReleased
        try{
            
            pStatement=con.prepareStatement("SELECT recover_code from adminlogin WHERE email=?");
            pStatement.setString(1,receiverMail);
            rs=pStatement.executeQuery();
            while(rs.next()){
                recode=rs.getString("recover_code");
            }
            if(recode.equals(codeTf.getText())){
                pass.setEditable(true);
                cpass.setEditable(true);
                showText.setText("set new Password");
            }
            else{
                showText.setText("Enter Correct code");
            }
        }
        catch(Exception excp){
            System.out.println(excp);
        }
    }//GEN-LAST:event_codeTfKeyReleased

    private void passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusGained
        pass.setText("");
    }//GEN-LAST:event_passFocusGained

    private void cpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpassFocusGained
        cpass.setText("");
    }//GEN-LAST:event_cpassFocusGained

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
       try{

            password1=new String(pass.getPassword());
            password2=new String(cpass.getPassword());
            generatepassword();
             if(password1.matches(password2)){
                
                pStatement=con.prepareStatement("UPDATE adminlogin SET password=?,salt_value=? WHERE email=?");
                pStatement.setString(1,mySecurePass);
                pStatement.setString(2,saltCode);
                pStatement.setString(3,receiverMail);
                pStatement.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Your New password is saved back to login");
                this.dispose();
                Login h=new Login();
                h.setVisible(true);
       }
             else{
                    JOptionPane.showMessageDialog(null,"Passward missmatch" );

               }
            }

            catch(Exception exc){
                System.out.println(exc);
            }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void codeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeTfActionPerformed
public void generatepassword(){
         
        // Generate Salt. The generated value can be stored in DB. 
        saltCode = PasswordManager.getSalt(30);        
        // Protect user's password. The generated value can be stored in DB.
        mySecurePass = PasswordManager.generateSecurePassword(password1, saltCode);
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetPassword().setVisible(true);
            }
        });
    }

    
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codeTf;
    private javax.swing.JPasswordField cpass;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JButton saveBtn;
    public javax.swing.JLabel showText;
    // End of variables declaration//GEN-END:variables
}
