/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diu.desk;

import com.itextpdf.text.Image;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
 
public class StudentCenter extends javax.swing.JFrame {
     Connection con = null;
     Statement statement = null;
     PreparedStatement pStatement = null;
     ResultSet rs = null;
     Image image;
     byte[] imagebyte;
    /**
     * Creates new form StudentCenter
     */
    public StudentCenter() {
        initComponents();
        con = ConnectionFactory.getMysqlConnection();
        studentInfoTF.setText(null);     
      studentInfoTF.setOpaque(false);      
      studentInfoTF.setBackground(new Color(0f,0f,0f,.3f));
      sipane.getViewport().setOpaque(false);
      sipane.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        studentIdTf = new javax.swing.JTextField();
        ImageLbl = new javax.swing.JLabel();
        sipane = new javax.swing.JScrollPane();
        studentInfoTF = new javax.swing.JTextArea();
        closebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Students'  Information Center ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 69, 79));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Students' Information Center");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 680, 50));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Search student by registration no.:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 230, 30));

        studentIdTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                studentIdTfKeyReleased(evt);
            }
        });
        jPanel1.add(studentIdTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 330, 30));
        jPanel1.add(ImageLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 140, 160));

        studentInfoTF.setEditable(false);
        studentInfoTF.setColumns(20);
        studentInfoTF.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        studentInfoTF.setForeground(new java.awt.Color(255, 255, 255));
        studentInfoTF.setRows(5);
        studentInfoTF.setOpaque(false);
        sipane.setViewportView(studentInfoTF);

        jPanel1.add(sipane, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 570, 300));

        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_26px.png"))); // NOI18N
        closebtn.setText("Close");
        closebtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        jPanel1.add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void studentIdTfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentIdTfKeyReleased
        if(evt.getKeyCode()== KeyEvent.VK_BACK_SPACE){
           studentInfoTF.setText(null); 
           ImageLbl.setIcon(null);
        }
        try {
         pStatement=con.prepareStatement("SELECT * FROM `studentinfo` WHERE student_id=?");
          pStatement.setString(1,studentIdTf.getText());
           rs=pStatement.executeQuery();
           while(rs.next()){
                      imagebyte=rs.getBytes("image");
                      java.awt.Image awtImage=getToolkit().createImage(imagebyte);
                      java.awt.Image reSiezedimg = awtImage.getScaledInstance(ImageLbl.getWidth(), ImageLbl.getHeight(),awtImage.SCALE_SMOOTH);
                      ImageIcon icon=new ImageIcon(reSiezedimg);                         
                      ImageLbl.setIcon(icon);
                      
             studentInfoTF.append
                    (" Student Name  : "+rs.getString("student_name")+'\n'+
                     " Roll No       : "+rs.getString("roll")+'\n'+
                     " Rege No       : "+rs.getString("student_id")+'\n'+
                     " Batch No      : "+rs.getString("batch")+'\n'+
                     " Semester      : "+rs.getString("semester")+'\n'+
                     " Department    : "+rs.getString("department")+'\n'+
                     " Fathers' Name : "+rs.getString("fathers_name")+'\n'+
                     " Mothers' Name : "+rs.getString("mothers_name")+'\n'+
                     " Mobile No     : "+rs.getString("mobile")+'\n'
                             
             
             );
           }
           
          
    }catch(Exception rs){
        System.out.println("Error"+rs);
       }
    }//GEN-LAST:event_studentIdTfKeyReleased

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentCenter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageLbl;
    private javax.swing.JButton closebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane sipane;
    private javax.swing.JTextField studentIdTf;
    private javax.swing.JTextArea studentInfoTF;
    // End of variables declaration//GEN-END:variables
}
