/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diu.desk;

import java.awt.Image;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

 
public class TeachersCenter extends javax.swing.JFrame {
 Connection con = null;
     Statement statement = null;
     PreparedStatement pStatement = null;
     ResultSet rs = null;
     Image image;
     byte[] imagebyte;
     String Teacherid;
      File file;
    BufferedImage im=null;
       
    /**
     * Creates new form TeachersCenter
     */
    public TeachersCenter(String Add) {
        initComponents();
       con = ConnectionFactory.getMysqlConnection();
       RemoveTeacher.setVisible(false);
       
    }
    
      public TeachersCenter(String Add, String Remove) {
        initComponents();
       con = ConnectionFactory.getMysqlConnection();      
       AddTeacher.setVisible(false);       
    }
    public TeachersCenter(){
       initComponents();
       con = ConnectionFactory.getMysqlConnection();
       AddTeacher.setVisible(false);
       RemoveTeacher.setVisible(false);
       
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ImageLbl = new javax.swing.JLabel();
        TeacherName = new javax.swing.JTextField();
        teacherId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        designationTf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        EmailId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        MobileNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CurrentLoad = new javax.swing.JTextField();
        AddTeacher = new javax.swing.JButton();
        RemoveTeacher = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Teachers' Information Center");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 69, 79));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Teacher info");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 680, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 120, 30));

        ImageLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(ImageLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 140, 150));

        TeacherName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TeacherNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TeacherNameKeyTyped(evt);
            }
        });
        jPanel1.add(TeacherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 310, 30));

        teacherId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teacherIdKeyReleased(evt);
            }
        });
        jPanel1.add(teacherId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 310, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Enter Teacher ID:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Designation:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 120, 30));

        designationTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                designationTfKeyReleased(evt);
            }
        });
        jPanel1.add(designationTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 310, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Email:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 120, 30));

        EmailId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EmailIdKeyReleased(evt);
            }
        });
        jPanel1.add(EmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 310, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Mobile No.:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 120, 30));

        MobileNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MobileNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MobileNoKeyTyped(evt);
            }
        });
        jPanel1.add(MobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 310, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Current Load:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 120, 30));

        CurrentLoad.setEditable(false);
        CurrentLoad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CurrentLoadKeyReleased(evt);
            }
        });
        jPanel1.add(CurrentLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 310, 30));

        AddTeacher.setText("Add Teacher");
        AddTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTeacherActionPerformed(evt);
            }
        });
        jPanel1.add(AddTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 140, 40));

        RemoveTeacher.setText("Remove This Teacher");
        RemoveTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveTeacherActionPerformed(evt);
            }
        });
        jPanel1.add(RemoveTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 160, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Upload Image");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TeacherNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TeacherNameKeyReleased
     
    }//GEN-LAST:event_TeacherNameKeyReleased

    private void teacherIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teacherIdKeyReleased
        if(evt.getKeyCode()== KeyEvent.VK_BACK_SPACE){
              Teacherid=null;
              ClearData();
            }
        try {
         pStatement=con.prepareStatement("SELECT teacherid,tname,designation,`load`,image,email,phone FROM `teachersinfo` WHERE `teacherid`=?");         
         pStatement.setString(1,teacherId.getText()); 
         rs=pStatement.executeQuery();
         if(rs.next()){
             Teacherid=rs.getString("teacherid");
             TeacherName.setText(rs.getString("tname"));
             designationTf.setText(rs.getString("designation"));
             CurrentLoad.setText(rs.getString("load"));
             MobileNo.setText(rs.getString("phone"));
             EmailId.setText(rs.getString("email"));
            imagebyte=rs.getBytes("image");
            if(imagebyte==null){
               ImageLbl.setIcon(null);
            }else{
            Image profileimage=getToolkit().createImage(imagebyte);
            Image reSiezedimg = profileimage.getScaledInstance(ImageLbl.getWidth(), ImageLbl.getHeight(),profileimage.SCALE_SMOOTH);
            ImageIcon icon=new ImageIcon(reSiezedimg);                         
            ImageLbl.setIcon(icon);
             }
            
             
         }
     } catch (SQLException ex) {
         Logger.getLogger(TeachersCenter.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_teacherIdKeyReleased

    private void designationTfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_designationTfKeyReleased
        
    }//GEN-LAST:event_designationTfKeyReleased

    private void EmailIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailIdKeyReleased
      
    }//GEN-LAST:event_EmailIdKeyReleased

    private void MobileNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MobileNoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_MobileNoKeyReleased

    private void CurrentLoadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CurrentLoadKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrentLoadKeyReleased

    private void AddTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTeacherActionPerformed
       
        System.out.println(Teacherid);
        if(Teacherid==null){ 
            if(teacherId.getText().equals("")){
                 JOptionPane.showMessageDialog(null, "You left to fill TeacherID");
            }else{
            if(TeacherName.getText().equals("")){
                 JOptionPane.showMessageDialog(null, "You left to fill Teacher Name");  
            }else{
                  if(designationTf.getText().equals("")){
                 JOptionPane.showMessageDialog(null, "You left to fill Designation");  
            }else{if(EmailId.getText().equals("")){
                 JOptionPane.showMessageDialog(null, "You left to fill Email");  
            }else{if(MobileNo.getText().equals("")){
                 JOptionPane.showMessageDialog(null, "You left to fill Mobile no");  
            }else{
         
          if(file==null){              
             JOptionPane.showMessageDialog(null, "You left upload image or insert data");  
          }else{
              boolean status=validateEmail(EmailId.getText());
               if(!status){
           JOptionPane.showMessageDialog(null, "Invalid Email\n Email Format Like: Example@email.com");
       }else{ 
                   try {
               FileInputStream fin = new FileInputStream(file);                 
                pStatement=con.prepareStatement("INSERT INTO `teachersinfo`(`tname`, `designation`, `image`, `email`, `phone`, `teacherid`) VALUES (?,?,?,?,?,?)");
                pStatement.setString(1, TeacherName.getText());
                pStatement.setString(2, designationTf.getText());
                pStatement.setBinaryStream(3,(InputStream)fin,(int)file.length());
                pStatement.setString(4, EmailId.getText());
                pStatement.setString(5,MobileNo.getText());
                pStatement.setString(6,teacherId.getText());
                ClearData();
                 teacherId.setText("");
                JOptionPane.showMessageDialog(null, "Teacher Added");
                 pStatement.execute();             
          } 
             catch (Exception ex) {
                Logger.getLogger(TeachersCenter.class.getName()).log(Level.SEVERE, null, ex);
            }
                   
               } }}
                  }}}
            
       }      
        }        
        else{
            JOptionPane.showMessageDialog(null, "Teacher is Alredy Existes");
       }
    }//GEN-LAST:event_AddTeacherActionPerformed

    
    public void ClearData(){        
         TeacherName.setText("");
         designationTf.setText("");
         CurrentLoad.setText("");
         MobileNo.setText("");
         EmailId.setText("");
         ImageLbl.setIcon(null);
    }
    
    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
       JFileChooser fc = new JFileChooser();
                int result = fc.showOpenDialog(null);
                if (result == JFileChooser.APPROVE_OPTION) {
                file = fc.getSelectedFile();
                    try {                       
                        im=ImageIO.read(file);            
            Image reSiezedimg = im.getScaledInstance(ImageLbl.getWidth(), ImageLbl.getHeight(),im.SCALE_SMOOTH);
            ImageIcon icon=new ImageIcon(reSiezedimg);
                        ImageLbl.setIcon(icon);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
         
    }//GEN-LAST:event_jLabel8MouseClicked

    private void MobileNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MobileNoKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c))||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_DELETE)
        evt.consume();
    }//GEN-LAST:event_MobileNoKeyTyped

    private void TeacherNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TeacherNameKeyTyped
        char n=evt.getKeyChar();
        if(!((Character.isAlphabetic(n)) ||n==KeyEvent.VK_PERIOD ||  n==KeyEvent.CHAR_UNDEFINED||n==KeyEvent.VK_BACK_SPACE||n==KeyEvent.VK_DELETE || n==KeyEvent.VK_SPACE))
        evt.consume();
    }//GEN-LAST:event_TeacherNameKeyTyped

    private void RemoveTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveTeacherActionPerformed
        int result= JOptionPane.showConfirmDialog(this, "Are you sure to Remove this Teacher!", "Confirmation",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
      if(result==0){
           try{
              pStatement=con.prepareStatement("DELETE FROM `teachersinfo` WHERE `teacherid`=?");                      
               pStatement.setString(1,teacherId.getText()); 
              pStatement.executeUpdate(); 
              JOptionPane.showMessageDialog(null, "Teacher Removed");
              ClearData(); teacherId.setText("");
              
        }
           catch(Exception exce){
             
           } }else{
          
      }
    }//GEN-LAST:event_RemoveTeacherActionPerformed
    
   public static boolean validateEmail(String email) {                 

                        
       boolean status=false;    
       String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
       Pattern pattern = Pattern.compile(EMAIL_PATTERN);
       Matcher matcher=pattern.matcher(email);
       if(matcher.matches())
       {
           status=true;
       }
       else{
           status=false;
       }
           return status;
            
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeachersCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeachersCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeachersCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeachersCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeachersCenter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTeacher;
    private javax.swing.JTextField CurrentLoad;
    private javax.swing.JTextField EmailId;
    private javax.swing.JLabel ImageLbl;
    private javax.swing.JTextField MobileNo;
    private javax.swing.JButton RemoveTeacher;
    private javax.swing.JTextField TeacherName;
    private javax.swing.JTextField designationTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField teacherId;
    // End of variables declaration//GEN-END:variables
}
